### ISSUE TITLE
help! I cannot list all the elections.

### ISSUE THREAD

**Issue by sunnycomes** [alainncls/vote-system#2]
I try to list all the elections, but error occurs as following,

```
index.js:185 Uncaught (in promise) Error: call revert exception (method="getElectionsNumber()", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.5.0)
    at Logger.makeError (index.js:185:1)
    at Logger.throwError (index.js:194:1)
    at Interface.decodeFunctionResult (interface.js:341:1)
    at Contract.<anonymous> (index.js:288:1)
    at Generator.next (<anonymous>)
    at fulfilled (index.js:5:43)
```

**Comment by alainncls** [comment]
Hey! Sorry about that.
Can you give me a little more context? What steps did lead you there?

**Comment by sunnycomes** [comment]
It's my fault, I did connect the website to metamask. Now it can list all the elections. Your demo is a great prototype of blockchain for others to study.
